plugins {
	id 'eclipse'
	id 'idea'
	id 'net.minecraftforge.gradle' version '6.+'
	id 'org.spongepowered.mixin' version '0.7.+'
	id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = '1.6'
group = 'bl4ckscor3.mod.biomeinfo'
archivesBaseName = 'biomeinfo-1.19.4'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

minecraft {
    mappings channel: 'parchment', version: '2023.06.26-1.19.4'
	
    runs {
        client {
		    workingDirectory project.file('run/client')
            property 'forge.logging.console.level', 'debug'

            mods {
                biomeinfo {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
	maven {
		url "https://cursemaven.com/"
		content {
			includeGroup "curse.maven"
		}
	}
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.19.4-45.1.0'
    implementation fg.deobf("curse.maven:configured-457570:4462894")
}

jar {
    manifest {
        attributes(["Specification-Title": "BiomeInfo",
                    "Specification-Vendor": "bl4ckscor3",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "BiomeInfo",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor" :"bl4ckscor3",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")],)
    }
}