plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'net.neoforged.gradle.userdev' version '7.0.+'
}

version = '1.6'
group = 'bl4ckscor3.mod.biomeinfo'

base {
	archivesName = 'biomeinfo-1.21.4'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

runs {
    client {
	    workingDirectory project.file('run/client')
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }
}

repositories {
	maven {
		url "https://cursemaven.com/"
		content {
			includeGroup "curse.maven"
		}
	}
}

dependencies {
	implementation 'net.neoforged:neoforge:21.3.64'
//	implementation "curse.maven:configured-457570:5340194"
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "BiomeInfo",
                    "Specification-Vendor": "bl4ckscor3",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "BiomeInfo",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor": "bl4ckscor3"],)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
	options.release = 21
}