# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G

# Fabric Properties
minecraft_version = 1.21.4
loader_version = 0.16.9

# Mod Properties
mod_version = 18
maven_group = bl4ckscor3.mod
archives_base_name = biomeinfo-1.21.4

# Dependencies
fabric_version=0.111.0+1.21.4
cloth_config_version = 17.0.142
modmenu_version = 13.0.0-beta.1