license="${license}"
issueTrackerURL="https://github.com/bl4ckscor3/BiomeInfo/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    description='''${description}'''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/biomeinfo"
    logoFile="assets/${mod_id}/icon.png"
    authors="${mod_author}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

