plugins {
    id 'net.neoforged.moddev' version "${mdg_version}"
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
            gameDirectory = mkdir(file("${run_dir}"))
            logLevel = org.slf4j.event.Level.DEBUG
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    compileOnly project(":common")
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}